TARGET = test_assign_frames_original
LIBS = -lcommons -lm
CC = gcc
CFLAGS = -g -Wall -I../ -I/home/utnso/Desktop/tp-final-v2/utils

DEPS = test_utils.h test_page_table_functions.h
OBJ = test_assign_frames_original.o test_page_table_functions.o

%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

$(TARGET): $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(LIBS)

.PHONY: clean

clean:
	rm -f $(OBJ) $(TARGET)
