name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up GCC and dependencies
      - name: Set up GCC and dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc make libcspecs-dev libreadline-dev

      # Build the utils library
      - name: Build utils library
        run: |
          make -C utils

      # Run tests for utils
      - name: Run tests for utils
        run: |
          make -C utils test
          echo "======= Running utils tests ======="
          ./utils/bin/utils_tests
