name: CI Utils Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  utils-tests:
    runs-on: ubuntu-latest
    name: Ejecutar tests de utils

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias de compilación
        run: |
          sudo apt update
          sudo apt install -y build-essential git

      - name: Instalar cspec desde Mumuki
        run: |
          git clone https://github.com/mumuki/cspec.git
          cd cspec
          make
          sudo make install

      - name: Ejecutar tests de utils
        working-directory: utils
        run: make test
